### ISSUE TITLE
Input labels

### ISSUE THREAD

**Issue by oliverjam** [fac19/week2-cica#28]
https://github.com/fac19/week2-cica/blob/e302e5f8d9bd6bf4eda0ad50f27edc23930ea1ff/index.html#L19-L29

It looks like you've tried to use the same `<label>` element for two different inputs. This doesn't work: each input element needs a unique label that describes what it's for. The `for` attribute can only take a single ID.

You can tell it's not working properly because clicking the label doesn't focus the associated input.

**Comment by oliverjam** [comment]
@CampbellDocherty it doesn't look like this is fixed yet? I can't see any code committed since midnight last night. It's generally best to leave issues open and close them in an associated commit/PR (using the `relates #issuenumber` syntax). If you're not planning on fixing it a common practice is to add a `wontfix` label (and maybe explain why 😅)

**Comment by CampbellDocherty** [comment]
@oliverjam hey sorry, I was fixing lots of issues and then I was gonna commit them all. I see now that I should've been committing every time I solved an issue.

**Comment by oliverjam** [comment]
Yeah it's best to do one "thing" per commit. This lets you provide more specific and useful messages than 'fixes issues' 😆 

Also: this one isn't quite fixed yet. You've now got a label nested _inside_ another label, which is also not valid. Each separate field should be a label + input
